
export const EDUCATION_LEVELS_COLORING = [
    "Otro (especificar)",
    "Educación Infantil",
    "Pre-escolar",
    "Grado 1",
    "Grado 2",
    "Grado 3",
    "Grado 4",
    "Grado 5",
    "Grado 6",
    "Grado 7",
    "Grado 8",
];

export const SUBJECTS_COLORING = [
    "Otro (especificar)",
    "Biología",
    "Ciencias Naturales",
    "Ciencias Sociales",
    "Economía",
    "Educación Artística y Cultural",
    "Educación Física, Recreación y Deportes",
    "Física",
    "Geografía",
    "Historia",
    "Inglés",
    "Matemáticas",
    "Química",
    "Lengua",
    "Español",
    "Literatura",
    "Religión",
    "Constitución Política y Democracia",
    "Ética y Valores Humanos",
    "Filosofía",
    "Tecnología e Informática",
    "Educación Ambiental",
    "Cátedra de Estudios Afrocolombianos",
    "Educación para la Ciudadanía",
    "Educación para la Paz",
    "Educación para la Sexualidad",
];
